Public Class Week4Form

    Private Sub Week4Form_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ' CRITICAL FIX: Transfer the Designer controls into the Base Form's container
        ' This ensures your base form's "Lesson Reviewer" UI doesn't swallow them
        If pnlContainer IsNot Nothing Then
            pnlContainer.Controls.Add(pnlLeft)
            pnlContainer.Controls.Add(lblLesson)

            ' Force them to the very top layer
            pnlLeft.BringToFront()
            lblLesson.BringToFront()
        End If
    End Sub

    ' 1. EVENT & METHOD DEMO: Clicking fires an event, MessageBox.Show is a method.
    Private Sub btnTestEvent_Click(sender As Object, e As EventArgs) Handles btnTestEvent.Click
        MessageBox.Show("The 'Click' Event was triggered!" & vbCrLf & "This popup is generated by the MessageBox.Show() Method.", "Method & Event Demo", MessageBoxButtons.OK, MessageBoxIcon.Information)
    End Sub

    ' 2. PROPERTY MANIPULATION DEMO: Changing object properties dynamically at runtime.
    Private Sub btnChangeProp_Click(sender As Object, e As EventArgs) Handles btnChangeProp.Click
        If txtDemo.BackColor = Color.FromArgb(45, 45, 48) Then
            ' Change Properties
            txtDemo.BackColor = Color.LimeGreen
            txtDemo.ForeColor = Color.Black
            txtDemo.Font = New Font(txtDemo.Font, FontStyle.Bold)
            txtDemo.Text = "Properties Changed Successfully!"
        Else
            ' Revert Properties
            txtDemo.BackColor = Color.FromArgb(45, 45, 48)
            txtDemo.ForeColor = Color.White
            txtDemo.Font = New Font(txtDemo.Font, FontStyle.Regular)
            txtDemo.Text = "Properties Reverted!"
        End If
    End Sub

    ' 3. ANCHOR & DOCK DEMO: Resizing the parent panel shows how child controls react.
    Private Sub btnResizePanel_Click(sender As Object, e As EventArgs) Handles btnResizePanel.Click
        ' We toggle the size of pnlLeft to demonstrate layout behaviors
        If pnlLeft.Width = 320 Then
            ' Shrink the panel
            pnlLeft.Size = New Size(220, 270)
            btnResizePanel.Text = "↔ Restore Panel Size"
        Else
            ' Restore the panel
            pnlLeft.Size = New Size(320, 375)
            btnResizePanel.Text = "↔ Resize Panel (Demo Anchor/Dock)"
        End If

        ' Notice that btnAnchored sticks to the bottom-right corner, 
        ' and pnlDockBottom stretches to fill the entire bottom width!
    End Sub

End Class